<?php

namespace App\StatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatRepository extends EntityRepository {

    public function findByFilters(array $filters = array()) {
        $queryBuilder = $this->createQueryBuilder('r');

        if (isset($filters['type']) && is_array($filters['type']) && count($filters['type'])) {
            $queryBuilder->andWhere($queryBuilder->expr()->in('r.type', array_values($filters['type'])));
        }

        // ~

        if (isset($filters['date_start']) && strlen($filters['date_start'])) {
            $queryBuilder->andWhere('r.createdAt >= :start');
            $queryBuilder->setParameter('start', $filters['date_start']);
        }

        // ~

        if (isset($filters['date_end']) && strlen($filters['date_end'])) {
            $queryBuilder->andWhere('r.createdAt <= :end');
            $queryBuilder->setParameter('end', $filters['date_end']);
        }

        return $queryBuilder->getQuery()->getResult();
    }

    /**
     * Get all distinct stats types
     * @return array
     */
    public final function findTypes() {
        $queryBuilder = $this->createQueryBuilder('r');
        $queryBuilder->distinct()->select('r.type');
        return $queryBuilder->getQuery()->getArrayResult();
    }

}
